kind = "web"
previewPath = "/"
title = "Numo"
version = "1.0.0"
id = "artifacts/numo"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25827

[services.development]
run = "pnpm --filter @workspace/numo run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/numo", "run", "build" ]
publicDir = "artifacts/numo/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25827"
BASE_PATH = "/"
